madzak/python-json-logger

setup.py, src/pythonjsonlogger/jsonlogger.py
Currently, fields in `exc_info` are serialized by simply calling str(), leading to a lack of exception and traceback information.
This PR adds support for proper serialization of traceback and exception types to ensure that the JSON result is usable for debugging.  The result:
Be aware that tests are currently failing against upstream master, and that issue is not introduced by, nor addressed in, this PR.
=> Handle error information in a more logical way

src/pythonjsonlogger/jsonlogger.py
The attribute "stack_info" was added in Python 3.2 as a reserved attribute for log records.
I considered adding it only as a reserved word for Python 3.2+ code but it's probably better to make it reserved in earlier Python versions as well in anticipation of an update to Python 3.x.
https://docs.python.org/3/library/logging.html#logrecord-attributes
=> Added "stack_info" as reserved attribute (introduced in Python 3.2)

src/pythonjsonlogger/jsonlogger.py, tests/tests.py
The standard formatter includes formatted exception information when log.exception is used. This pull request adds the same formatted exception under the key "exc_info" in the output JSON.
This is included in the message_dict, so a user can override the exc_info if it's set in the extra dict (or message dict). This also means that %(exc_info)s does not need to be included in the format string to include the exception information.
=> Add exception information to output when present.

src/pythonjsonlogger/jsonlogger.py
Right now I'm implementing tests of a logging module, and would like to test the output of the `JsonFormatter` with the fields I'm supplying.  I can create an `OrderedDict` and dump it to json using the `json_default` and `json_encoder` attrs of `JsonFormatter`, but it would be better if my code didn't need to know the implementation details of `JsonFormatter`.  I think that this would be a generally useful abstraction to make.
=> Added a jsonify_log_record method to help testing.

src/pythonjsonlogger/jsonlogger.py, tests/tests.py
Hi,
here are some suggestions:
* in the current default JSON serializer, seconds are lost in `datetime` instances
* in my opinion, the `datefmt` parameter to `logging.Formatter` instances should be used only to format the message time; not to serialize the data
* testJsonLogger has been renamed to TestJsonLogger
Regards.
=> Suggestions: second are lost in default date serialization + XML test broken

src/pythonjsonlogger/jsonlogger.py
I explain the reason and some background [here](https://github.com/amitsaha/python-json-logging/tree/master/multi_processes_queue_logger), let me know if you want me to write a test for it.
=> Set exc_info to exc_text (if available) and if exc_info is not set

.travis.yml, README.markdown
Tests for Python 2.6, 2.7, 3.2, 3.3, 3.4 are run in parallel.
Most scripting and interaction handled by [tox-travis][1] package.
Notes:
* [Python 3.1 envs not supported by Travis][2] and are omitted.
* Allow failure for Python 2.6 for the moment.
[1]: https://github.com/ryanhiebert/tox-travis
[2]: https://github.com/travis-ci/travis-ci/issues/1826
=> Add Travis CI support

tests/tests.py
The Formatter class in the logging package of Python 2.6 is old style.
To be able to still run the test on Python 2.6, this needs to be the old style "super".
=> Fix Custom Logic Adds Field test for Python 2.6

.travis.yml
This encompasses #39 and #40 with the "addition" of removing Python 2.6 from the list of allowed failures. Merging this in will close those too.
=> Python 2.6 test fix and travis ci

src/pythonjsonlogger/jsonlogger.py
The stdlib JSON encoder is quite slow. This PR lets people use simplejson, UltraJSON, etc.
=> Allow alternative JSON encoders

src/pythonjsonlogger/jsonlogger.py
This essentially just allows instances of JsonFormatter or its subclasses to set a flag that controls the indentation of the output JSON.
=> Allows pretty printing of JSON messages w/ cls kwarg

setup.py, src/pythonjsonlogger/jsonlogger.py
Adds a custom `JsonEncoder` class that can be extended, and creates/documents a few more kwargs that can be passed to `JsonFormatter` to modify its behavior. Should be backwards compatible with any existing configurations.
I added the two classifiers because I ran the tests against Python 3.5 and 3.6 and I'm currently using this package in production with Python 3.6. It also seems like the tox config is already running this project against Python 3.5 and 3.6.
=> Extend extensibility

.travis.yml, setup.py, tox.ini
Python 2.6, Python 3.1, Python 3.2 and Python 3.3 have reached end-of-life: https://devguide.python.org/#status-of-python-branches.
=> Only support Python 2.7, 3.4, 3.5 and 3.6

src/pythonjsonlogger/jsonlogger.py
This commit aims to achieve consistent stack frames control
by `stack_info` flag in logging calls the same as that in python
logging module.
Currently, both a field named `stack_info` for JsonFormatter
and `stack_info=True` for logging function are needed for
stack frames to be properly displayed.
If `stack_info` field name is not passed, no output is given
irrespective of the `stack_info` flag in logging calls.
If `stack_info=False` in logging calls and `stack_info` is also
passed as one field for JsonFormatter, the output is `{"stack_info": null}`.
Above behavior is not very consistent and requires two controls
to output stack frames. This commit makes 'stack_info' flag in logging calls
as single point control of stack frames output and there is no need to
pass `stack_info` field into …
=> Consistent control of stack_info

src/pythonjsonlogger/jsonlogger.py
Hi. The purpose of this PR is to move the final log record serialization to a separate method from the main .format(). This will improve customization of the class. Here is my case:
I want to send logs to google stackdriver from my python application. I am using json-logger to get structured log record with all `extra` fields, but stackdriver python library won't parse a string that contains an encoded json you need to pass a python dict object to it. 
So I would like to use all features of the json-logger except actual json encoding to receive python dict objects as the output. 
What do you think?
=> Move log record serialization to a separate method.

src/pythonjsonlogger/jsonlogger.py, tests/tests.py
The "timestamp" field does not contain timezone information. If you don't live in GMT, that is probably wrong for you. This PR adds an additional "+000" to the serialized datetime.
Also, it uses the log creation timestamp, not whatever time it is when the field gets added.
=> Add timezone to timestamp

.travis.yml, README.md, setup.py, tests/tests.py, tox.ini
See #86 
See #74 
This PR fixes up a couple of small issues encountered when upgrading to Python 3.8:
- updates examples in `README.md` to be compatible with Python 3.8
- updates test code to match the formatting example provided in the readme
- adds Python 3.8 testing to Travis and tox
- marks the package as Python 3.8 compatible in `setup.py`
=> Update examples and tests for Python 3.8 compatibility

src/pythonjsonlogger/jsonlogger.py, tests/tests.py
This merge requests allows to rename field names in the output with something else, like "message" to "@message".
=> Allow to rename standard field names

src/pythonjsonlogger/jsonlogger.py, tests/tests.py
Adds the kwarg `static_fields` to add a dict of fields with a static value to every log entry, in case a simple descriptor is needed in a logger.
This way fields can be added editing only logger configuration and no code is needed.
=> Add static_fields arg to add common, fixed fields to all logs

src/pythonjsonlogger/jsonlogger.py
This PR should make it possible to use any of the following string formats: `"%(message)s"`, `"{message}"`, or `"${message}"`.
=> Adding support for all string formatting styles: '%', '$', or '{'.

.github/workflows/build.yml, tox.ini
To allow for typing annotations and enforcement of typing annotations,
we need to:
- Drop Python 3.5 support since it doesn't support the syntax
- Drop pypy 3.6 support since it doesn't support mypy
See https://github.com/madzak/python-json-logger/pull/129#issuecomment-1030708627 for additional background.
=> Drop Python 3.5 support and pypy 3.6 support

setup.cfg, setup.py, src/pythonjsonlogger/jsonlogger.py, src/pythonjsonlogger/py.typed, tox.ini
- Add a PEP 561 marker
- Add basic mypy configuration
- Run mypy from tox
- Minor code modifications to make mypy happy
This is intended to be a relatively minimal change just to enable basic type checking. Future changes should fill out the type annotations more and enable stricter mypy configuration (set all mypy options to 'true').
This change is a small step towards https://github.com/madzak/python-json-logger/issues/118
Note that the marker is intentionally not shipped via setup.py -- the annotations need more cleanup first (turn on a few key mypy config options, e.g. no-untyped-defs).
=> Add PEP 561 marker

src/pythonjsonlogger/jsonlogger.py
since 88838bd9 `OrderedDict` is imported unconditionally, so there is no need anymore for a `try-except NameError` anymore
=> Remove unnecessary try-except around OrderedDict usage

setup.cfg, src/pythonjsonlogger/jsonlogger.py
I would love to avoid doing this, but I can't seem to find a nicer alternative (without changing the API). Any thoughts on alternatives would her appreciated.
**Note that this may be a breaking change for typed code.** They'll need a "# type: ignore" comment if they want to pass in something other than a LogRecord and exercise this functionality.
See the related comment over at: https://github.com/madzak/python-json-logger/issues/118#issuecomment-1030888274
Note that logging.LogRecord.msg and logging.LogRecord.message are both type of str in typeshed (https://github.com/python/typeshed/blob/b88a6f19cdcf031be8135941b940f839e13064d8/stdlib/logging/__init__.pyi#L343) , but we treat them as (optional) dicts here.
=> Workaround logging.LogRecord.msg type of str

src/pythonjsonlogger/jsonlogger.py, tests/tests.py
The regression was introduced in 0055dc5b273949ee7432665eeddbe37781d9dc01.
Only fields followed by an `s` were correctly extracted.
As there are other possible cases like `8s`, `d`, or no prefix at all the regex is loosened.
In this funky case `[%(levelname)8s][PID %(process)d][%(threadName)s]` the extracted field was `levelname)8s][PID %(process)d][%(threadName`.
=> Fix too strict regex for pecentage style logging

.gitignore, setup.cfg, setup.py, src/pythonjsonlogger/jsonlogger.py, tests/tests.py, tox.ini
Address the issue #153 
Python2 sunset was in the January 1st 2020: https://www.python.org/doc/sunset-python-2/
`python3.5` and `python3.6` EOL dates are also passed: https://endoflife.date/python
=> Drop old python version support

setup.py
I'm trying to use `python-json-logger` in my project, but `mypy` is surfacing this error:
```text
error: Skipping analyzing "pythonjsonlogger": module is installed, but missing library stubs or py.typed marker
note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
```
I believe there is an open issue related to this: https://github.com/madzak/python-json-logger/issues/118
My guess why this continues to happen even though `py.typed` exists in the repo is because it isn't added to the package.
=> Add `py.typed` to package

tests/tests.py
Rename variables and functions in the tests to follow PEP8 principle
=> Refactor the unit tests

src/pythonjsonlogger/jsonlogger.py, tests/tests.py
Current `rename_fields` feature does not work for `exc_info`, as said in [this comment](https://github.com/madzak/python-json-logger/issues/36#issuecomment-732769603).
I've changed how the rename works and added a few more tests.
=> Fix rename_fields for exc_info

src/pythonjsonlogger/jsonlogger.py, tests/tests.py
Fixes https://github.com/madzak/python-json-logger/issues/163
In version `2.0.5` a new, non-optional argument to `merge_record_extra` was added, making the version non-backward-compatible.
- Make that new argument optional.
- Add test case making sure the method can be called without the argument.
=> Make argument optional

setup.py
The `py.typed` marker file, which indicates that the code has type annotations, is currently missing from the package files published on pypi. The reason is that the `package_data` dictionary in `setup.py` currently uses the key `"src/pythonjsonlogger"` where a package name, not a directory, is required (see [the example in the documentation][1]).
When the package name is used instead, `py.typed` gets packaged correctly.
[1]: https://setuptools.pypa.io/en/latest/userguide/datafiles.html#package-data
=> Fix inclusion of `py.typed` in pip packages
